manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: niceviewflip
      url-base: https://github.com/invrtd
  projects:
    - name: zmk
      remote: niceviewflip
      revision: nice!view-180
      import: app/west.yml
  self:
    path: config
